---
- group_by: key={{ ansible_os_family }}

- name: Install nginx on Ubuntu
  apt: name=nginx
  when: ansible_os_family == 'Debian'

- name: Enable nginx repo on CentOS
  yum: name=http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
  when: ansible_os_family == 'RedHat'

- name: Install nginx on CentOS
  yum: name=nginx
  when: ansible_os_family == 'RedHat'

- name: Clone drupal.conf from repository
  git: repo=https://github.com/axai-mx/simple-drupal-nginx.git dest=/etc/nginx/simple-drupal-nginx/
  notify: restart nginx

- name: Set worker processes for nginx
  lineinfile: dest=/etc/nginx/nginx.conf regexp='worker_processes' line='worker_processes auto;'
  notify: restart nginx

- name: Enable gzip
  lineinfile: dest=/etc/nginx/nginx.conf regexp='gzip\s+on' line='  gzip on;'
  notify: restart nginx

- name: Disable gzip for IE6
  lineinfile: dest=/etc/nginx/nginx.conf regexp='gzip_disable' insertafter='gzip on' line='  gzip_disable "msie6";'
  notify: restart nginx

- name: Enable gzip only for text files
  lineinfile: dest=/etc/nginx/nginx.conf regexp='gzip_types' insertafter='gzip on' line='  gzip_types application/atom+xml application/javascript application/json application/rss+xml application/vnd.ms-fontobject application/x-font-ttf application/x-web-app-manifest+json application/xhtml+xml application/xml font/opentype image/svg+xml image/x-icon text/css text/plain text/x-component;'
  notify: restart nginx

- name: Ensure nginx is started and enabled to start at boot.
  service: name=nginx state=started enabled=yes
